openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample OpenAPI definition for a basic API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: John Doe
                  email:
                    type: string
                    example: john.doe@example.com
        "404":
          description: User not found
        "500":
          description: Internal server error
